name: Update Blocklist

on:
  schedule:
    - cron: '34 12 * * *'  # Runs daily at 12:34 UTC
  workflow_dispatch:

jobs:
  update-blocklist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install requirements
        run: pip install requests

      - name: Run blocklist fetch + merge
        run: python scripts/update_blocklist.py

      - name: Upload blocklist as artifact
        uses: actions/upload-artifact@v4
        with:
          name: blocklist
          path: blocklist.txt
