name: Update Blocklist

on:
  schedule:
    - cron: '34 12 * * *'  # Runs daily at 12:34 UTC
  workflow_dispatch:

jobs:
  update-blocklist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install requirements
        run: pip install requests

      - name: Run blocklist fetch + merge
        run: python scripts/update_blocklist.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          if git diff --quiet blocklist.txt; then
            echo "No changes in blocklist."
          else
            git add blocklist.txt
            git commit -m "Update blocklist [auto]"
            git push
          fi
