name: Update Blocklist

on:
  schedule:
    - cron: '34 12 * * *'  # Runs every 12:34 hours at 00:00 UTC
  workflow_dispatch:      # Allows manual triggering

jobs:
  update-blocklist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install requirements (if needed)
        run: pip install requests

      - name: Fetch, merge, deduplicate, and sort blocklist
        run: |
          URLS=(
            "https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt"
            "https://adguardteam.github.io/HostlistsRegistry/assets/filter_10.txt"
            "https://adguardteam.github.io/HostlistsRegistry/assets/filter_11.txt"
            "https://adguardteam.github.io/HostlistsRegistry/assets/filter_12.txt"
            "https://adguardteam.github.io/HostlistsRegistry/assets/filter_18.txt"
            "https://adguardteam.github.io/HostlistsRegistry/assets/filter_23.txt"
            "https://adguardteam.github.io/HostlistsRegistry/assets/filter_3.txt"
            "https://adguardteam.github.io/HostlistsRegistry/assets/filter_30.txt"
            "https://adguardteam.github.io/HostlistsRegistry/assets/filter_31.txt"
            "https://adguardteam.github.io/HostlistsRegistry/assets/filter_33.txt"
            "https://adguardteam.github.io/HostlistsRegistry/assets/filter_4.txt"
            "https://adguardteam.github.io/HostlistsRegistry/assets/filter_42.txt"
            "https://adguardteam.github.io/HostlistsRegistry/assets/filter_50.txt"
            "https://adguardteam.github.io/HostlistsRegistry/assets/filter_53.txt"
            "https://adguardteam.github.io/HostlistsRegistry/assets/filter_57.txt"
            "https://adguardteam.github.io/HostlistsRegistry/assets/filter_59.txt"
            "https://adguardteam.github.io/HostlistsRegistry/assets/filter_7.txt"
            "https://adguardteam.github.io/HostlistsRegistry/assets/filter_8.txt"
            "https://adguardteam.github.io/HostlistsRegistry/assets/filter_9.txt"
            "https://badmojr.gitlab.io/1hosts/Pro/unbound.conf"
            "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/unbound/dyndns.blacklist.conf"
            "https://oooo.b-cdn.net/blahdns/blahdns_unbound.conf"
            "https://pgl.yoyo.org/adservers/serverlist.php?hostformat=unbound&showintro=0"
            "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/ultimate.txt"
            "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/ultimate.txt"
            "https://raw.githubusercontent.com/mr-narender/domain_filter/refs/heads/main/for_ad_blocklist.txt"
            "https://raw.githubusercontent.com/ph00lt0/blocklists/master/unbound-blocklist.txt"
            "https://raw.githubusercontent.com/r0xd4n3t/pihole-adblock-lists/main/pihole_adlists.txt"
          )

          TMPFILE=$(mktemp)
          for URL in "${URLS[@]}"; do
            curl -fsSL "$URL" >> "$TMPFILE" || echo "Failed to fetch $URL"
          done

          sort -u "$TMPFILE" > blocklist.txt
          rm "$TMPFILE"

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          if git diff --quiet blocklist.txt; then
            echo "No changes in blocklist."
          else
            git add blocklist.txt
            git commit -m "Update blocklist [auto]"
            git push
          fi
